---
# tasks file for telegraf

- name: Install telegraf
  apt:
    deb: "https://dl.influxdata.com/telegraf/releases/telegraf_1.5.2-1_amd64.deb"

- name: Render template
  template: 
    src: "{{ template_location }}"
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
